project:
  type: website
  output-dir: docs
  # render:
  #   - slides.qmd
  #   # - index.qmd
  preview:
    port: 4269

filters:
  - include-code-files
title: "Parallel Training Techniques"
date: today
date-modified: last-modified
favicon: "./favicon.svg"
author-title: ""
affiliation-title: ""
published-title: ""
modified-title: ""
title-block-categories: false
number-sections: false
bibliography: references.bib
appendix-cite-as: display
google-scholar: true
google-analytics: G-XVM2Y822Y1
author:
  # name: Sam Foreman
  name: "Sam Foreman [[{{< ai orcid >}}]{.orcid-green}](https://orcid.org/0000-0002-9981-0876)"
  url: https://samforeman.me
  # orcid: 0000-0002-9981-0876
  email: foremans@anl.gov
  affiliation: Argonne National Laboratory
  affiliation-url: https://alcf.anl.gov/about/people/sam-foreman
  # affiliation: Argonne National Laboratory
  # affiliation-url: https://alcf.anl.gov/about/people/sam-foreman
citation:
   author: Sam Foreman
   type: speech
   title: "Parallel Training Techniques"
   url: https://saforem2.github.io/parallel-training-slides
# favicon: "./assets/favicon.svg"
# format:
#   html:
#     syntax-definitions:
#       - ./docs/python.xml
#
website:
  open-graph:
    title: "Sam Foreman"
    description: "Parallel Training Techniques"
    image: "https://github.com/saforem2/parallel-training-slides/blob/main/assets/thumbnail.png?raw=true"
  twitter-card:
    site: "@saforem2"
    creator: "@saforem2"
    title: "Parallel Training Techniques"
    image: "https://github.com/saforem2/parallel-training-slides/blob/main/assets/thumbnail.png?raw=true"
  favicon: "./favicon.svg"
  description: "Parallel Training Techniques"
  page-navigation: true
  title: "Parallel Training Techniques"
  site-url: "https://saforem2.github.io/parallel-training-slides"
  # favicon: "./favicon.svg"
  back-to-top-navigation: true
  # reader-mode: true
  repo-url: https://github.com/saforem2/parallel-training-slides
  repo-actions: [source, edit, issue]
  google-analytics: G-XVM2Y822Y1
  sidebar: false
  # open-graph: true
  navbar:
    logo: "./favicon.svg"
    background: "#222222"
    foregound: "#777777"
    right:
      - icon: github
        href: https://github.com/saforem2/parallel-training-slides
        aria-label: GitHub
  page-footer:
    left: "[samforeman.me](https://samforeman.me)"
    right: "Copyright 2023, Sam Foreman" 
    center:
      - href: https://samforeman.me
        text: "{{< fa solid home >}}"
      - icon: github
        href: https://github.com/saforem2
      - icon: twitter
        href: https://twitter.com/saforem2
      - href: "mailto:///foremans@anl.gov"
        text: "{{< fa regular paper-plane >}}"
      - href: https://www.twitter.com/saforem2
        text: "{{< fa brands twitter >}}"
      - href: https://scholar.google.com/citations?user=vV_1zDwAAAAJ&hl=en
        text: "{{< ai google-scholar >}}"
      - href: https://orcid.org/0000-0002-9981-0876
        text: "{{< ai orcid >}}"
      - href: https://www.last.fm/user/saforem2
        text: "{{< fa brands lastfm >}}"
      - href: https://open.spotify.com/user/saforem2
        text: "{{< fa brands spotify >}}"
      - href: https://www.instagram.com/saforem2
        text: "{{< fa brands instagram >}}"
      - href: https://linkedin.com/in/saforem2
        text: "{{< fa brands linkedin >}}"

format:
  html:
    callout-appearance: simple
    # code-link: true
    code-line-numbers: false
    toc: true
    self-contained: false
    toc-location: right
    grid:
      body-width: 1150px
    fig-responsive: true
    anchor-sections: true
    # highlight-style: atom-one
    code-overflow: scroll
    code-fold: false
    code-copy: false
    code-summary: " "
    code-tools:
      source: repo
      toggle: true
      caption: none
    html-math-method: katex
    # css:
    #   - css/default.css
    #   - css/callouts.css
    #   # - css/profile.css
    # theme:
    #   light:
    #     - css/common.scss
    #     - css/light.scss
    #     - css/syntax-light.scss
    #     - css/callout-cards.scss
    #   dark:
    #     - css/common.scss
    #     - css/dark.scss
    #     - css/syntax-dark.scss
    #     - css/callout-cards.scss
    smooth-scroll: false
    citations-hover: true
    footnotes-hover: true
    # header-includes: |
    #   <link href="https://pvinis.github.io/iosevka-webfont/3.4.1/iosevka.css" rel="stylesheet" />
  # revealjs:
  #   code-line-numbers: false
  #   code-link: false
  #   code-copy: false
  #   # callout-appearance: simple
  #   # syntax-definitions:
  #   #   - ./docs/python.xml
  #   scrollable: true
  #   title-block-style: none
  #   slide-number: c
  #   title-slide-style: default
  #   chalkboard:
  #     buttons: false
  #   auto-animate: true
  #   reference-location: section
  #   # touch: true
  #   # pause: false
  #   # footnotes-hover: true
  #   # citations-hover: true
  #   preview-links: true
  #   controls-tutorial: true
  #   controls: false
  #   history: false
  #   highlight-style: "atom-one"
  #   css:
  #     - css/default.css
  #     - css/callouts-html.css
  #   theme:
  #     - white
  #     - css/light.scss
  #     - css/common.scss
  #     - css/syntax-light.scss
  #   self-contained: false
  #   embed-resources: false
  #   self-contained-math: false
  #   center: true
  #   default-image-extension: svg
  #   code-overflow: scroll
  #   html-math-method: katex
  #   fig-align: center
  #   mermaid:
  #     theme: dark
  # gfm:
  #   output-file: "readme.md"
  # revealjs:
  #   code-line-numbers: false
  #   code-link: false
  #   code-copy: false
  #   # callout-appearance: simple
  #   # syntax-definitions:
  #   #   - ./docs/python.xml
  #   scrollable: true
  #   title-block-style: none
  #   slide-number: c
  #   title-slide-style: default
  #   chalkboard:
  #     buttons: false
  #   auto-animate: true
  #   reference-location: section
  #   touch: true
  #   pause: false
  #   footnotes-hover: true
  #   citations-hover: true
  #   preview-links: true
  #   controls-tutorial: true
  #   controls: false
  #   logo: "assets/anl.svg"
  #   history: false
  #   highlight-style: "atom-one"
  #   # theme: [dark, css/dark.scss]
  #   # css: [css/default.css, css/callouts-html.css]
  #   css:
  #     - css/default.css
  #     - css/callouts-html.css
  #   # theme: [css/light.scss, css/common.scss, css/syntax-light.scss]
  #   theme:
  #     - white
  #     # - css/light.scss
  #     - css/common.scss
  #     - css/syntax-light.scss
  #     - css/pdf.scss
  #     # dark:
  #     #   - css/dark.scss
  #     #   - css/common.scss
  #     #   - css/syntax-dark.scss
  #   # css: [css/default.css, css/callouts.css, css/code-callout.css]
  #   self-contained: false
  #   embed-resources: false
  #   self-contained-math: false
  #   center: true
  #   default-image-extension: svg
  #   code-overflow: scroll
  #   html-math-method: katex
  #   fig-align: center
  #   mermaid:
  #     theme: dark
  # gfm:
  #   author: sam foreman
  #   output-file: "readme.md"
# include-in-header:
#   text: |
#     <script src="https://unpkg.com/shiki"></script>
#     <script>
#       shiki
#         .gethighlighter({
#           theme: 'dracula',
#           langs: ['python', 'html', 'bash', 'markdown', 'js', 'css'],
#         })
#         .then(highlighter => {
#           const code = highlighter.codetohtml(`console.log('shiki');`, { lang: 'js' })
#             document.getelementbyid('output').innerhtml = code
#         })
#     </script>
   # genre: "presentation at the 2023 international symposium on lattice field theory"
   # container-title: https://indico.fnal.gov/event/57249/contributions/271305/
   # title: "mlmc: machine learning monte carlo for lattice gauge theory"
   # url: https://saforem2.github.io/lattice23
   # abstract: | 
   #   we present a trainable framework for efficiently generating gauge
   #   configurations, and discuss ongoing work in this direction. in particular, we
   #   consider the problem of sampling configurations from a 4d 𝑆𝑈(3) lattice gauge
   #   theory, and consider a generalized leapfrog integrator in the molecular
   #   dynamics update that can be trained to improve sampling efficiency.
  # -----------------------
  # type: article-journal
  # container-title: acm transactions on embedded computing systems
  # volume: 21
  # issue: 2
  # issued: 2022-03
  # issn: 1539-9087
  # doi: 10.1145/3514174
  # -----------------------
  # type: speech
  # container-title: "journal of data science software"
  # doi: "10.23915/reprodocs.00010"
  # url: https://example.com/summarizing-output
  # -----------------------

#
#
#
#
#
# # website:
# #   page-navigation: true
# #   title: "mlmc: machine learning monte carlo"
# #   # site-url: "https://saforem2.github.io/mlmc"
# #   # favicon: "./assets/favicon.svg"
# appendix-cite-as: display	
# citation:
#    type: speech
#    genre: "presentation at the 2023 international symposium on lattice field theory"
#    container-title: https://indico.fnal.gov/event/57249/contributions/271305/
#    title: "mlmc: machine learning monte carlo for lattice gauge theory"
#    url: https://saforem2.github.io/lattice23
# author:
#   - name: sam foreman
#     # id: sf
#     url: https://samforeman.me
#     orcid: 0000-0002-9981-0876
#     email: foremans@anl.gov
#     affiliation: "argonne national laboratory"
#     affiliation-url: https://alcf.anl.gov/about/people/sam-foreman
#
#     # affiliation: 
#     #   - name: argonne national laboratory
#     #     city: chicago
#     #     state: il
#     #     url: https://alcf.anl.gov
#     #
# favicon: "./assets/favicon.svg"
# google-analytics: g-xvm2y822y1
# # title: a published conference paper
# # author:
# #   - name: norah jones
# #     affiliation: School of Hard Knocks
# #     orcid: 0000-0001-8715-9476
# # citation:
# #   type: paper-conference
# #   container-title: "Proceedings of the annual conference of the Society for Research"
# #   publisher: "Society for Research"
# #   issued: 2020/09/23
# #   volume: 2
# #   doi: "10.23915/reprodocs.00010"
# #   url: https://example.com/summarizing-output
# #   page-first: 46
# #   page-last: 53
# #   editor:
# #   - Don Draper
# #   - Nick Fury
# # google-scholar: true  
# #
# #
# # affiliation: ""
# # date: ""
# # toc: true
# filters:
#   - lua/callouts.lua
# highlight-style:
#   dark: dracula
#   light: dracula-light

